baseURL = "http://example.org/"
languageCode = "en-us"
title = "Featured Projects of David Zellhöfer - www.8bit-inferno.de"
# Novela settings
theme = "novela-david"

paginate = 6

[social]
twitter= "https://twitter.com/dzellhf"
github= "https://github.com/elektrobohemian"
linkedin= "#"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

